#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resturant
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="nnn")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insertcopon(copon instance);
    partial void Updatecopon(copon instance);
    partial void Deletecopon(copon instance);
    partial void Insertrole(role instance);
    partial void Updaterole(role instance);
    partial void Deleterole(role instance);
    partial void Insertcustomer(customer instance);
    partial void Updatecustomer(customer instance);
    partial void Deletecustomer(customer instance);
    partial void Insertday(day instance);
    partial void Updateday(day instance);
    partial void Deleteday(day instance);
    partial void Insertemployee(employee instance);
    partial void Updateemployee(employee instance);
    partial void Deleteemployee(employee instance);
    partial void Insertmenu(menu instance);
    partial void Updatemenu(menu instance);
    partial void Deletemenu(menu instance);
    partial void Insertorder(order instance);
    partial void Updateorder(order instance);
    partial void Deleteorder(order instance);
    partial void Insertresturant(resturant instance);
    partial void Updateresturant(resturant instance);
    partial void Deleteresturant(resturant instance);
    partial void Insertfood(food instance);
    partial void Updatefood(food instance);
    partial void Deletefood(food instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::Resturant.Properties.Settings.Default.nnnConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<copon> copons
		{
			get
			{
				return this.GetTable<copon>();
			}
		}
		
		public System.Data.Linq.Table<role> roles
		{
			get
			{
				return this.GetTable<role>();
			}
		}
		
		public System.Data.Linq.Table<customer> customers
		{
			get
			{
				return this.GetTable<customer>();
			}
		}
		
		public System.Data.Linq.Table<day> days
		{
			get
			{
				return this.GetTable<day>();
			}
		}
		
		public System.Data.Linq.Table<employee> employees
		{
			get
			{
				return this.GetTable<employee>();
			}
		}
		
		public System.Data.Linq.Table<menu> menus
		{
			get
			{
				return this.GetTable<menu>();
			}
		}
		
		public System.Data.Linq.Table<order> orders
		{
			get
			{
				return this.GetTable<order>();
			}
		}
		
		public System.Data.Linq.Table<resturant> resturants
		{
			get
			{
				return this.GetTable<resturant>();
			}
		}
		
		public System.Data.Linq.Table<food> foods
		{
			get
			{
				return this.GetTable<food>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.copon")]
	public partial class copon : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id_copon;
		
		private System.Nullable<double> _discount_;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnId_coponChanging(int value);
    partial void OnId_coponChanged();
    partial void Ondiscount_Changing(System.Nullable<double> value);
    partial void Ondiscount_Changed();
    #endregion
		
		public copon()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_copon", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Id_copon
		{
			get
			{
				return this._Id_copon;
			}
			set
			{
				if ((this._Id_copon != value))
				{
					this.OnId_coponChanging(value);
					this.SendPropertyChanging();
					this._Id_copon = value;
					this.SendPropertyChanged("Id_copon");
					this.OnId_coponChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[discount ]", Storage="_discount_", DbType="Float")]
		public System.Nullable<double> discount_
		{
			get
			{
				return this._discount_;
			}
			set
			{
				if ((this._discount_ != value))
				{
					this.Ondiscount_Changing(value);
					this.SendPropertyChanging();
					this._discount_ = value;
					this.SendPropertyChanged("discount_");
					this.Ondiscount_Changed();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.roles")]
	public partial class role : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_job;
		
		private System.Nullable<int> _id_employee;
		
		private string _work_hours;
		
		private string _workdays;
		
		private string _holidays;
		
		private string _job_name;
		
		private EntitySet<employee> _employees;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_jobChanging(int value);
    partial void Onid_jobChanged();
    partial void Onid_employeeChanging(System.Nullable<int> value);
    partial void Onid_employeeChanged();
    partial void Onwork_hoursChanging(string value);
    partial void Onwork_hoursChanged();
    partial void OnworkdaysChanging(string value);
    partial void OnworkdaysChanged();
    partial void OnholidaysChanging(string value);
    partial void OnholidaysChanged();
    partial void Onjob_nameChanging(string value);
    partial void Onjob_nameChanged();
    #endregion
		
		public role()
		{
			this._employees = new EntitySet<employee>(new Action<employee>(this.attach_employees), new Action<employee>(this.detach_employees));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_job", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id_job
		{
			get
			{
				return this._id_job;
			}
			set
			{
				if ((this._id_job != value))
				{
					this.Onid_jobChanging(value);
					this.SendPropertyChanging();
					this._id_job = value;
					this.SendPropertyChanged("id_job");
					this.Onid_jobChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_employee", DbType="Int")]
		public System.Nullable<int> id_employee
		{
			get
			{
				return this._id_employee;
			}
			set
			{
				if ((this._id_employee != value))
				{
					this.Onid_employeeChanging(value);
					this.SendPropertyChanging();
					this._id_employee = value;
					this.SendPropertyChanged("id_employee");
					this.Onid_employeeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_work_hours", DbType="NVarChar(50)")]
		public string work_hours
		{
			get
			{
				return this._work_hours;
			}
			set
			{
				if ((this._work_hours != value))
				{
					this.Onwork_hoursChanging(value);
					this.SendPropertyChanging();
					this._work_hours = value;
					this.SendPropertyChanged("work_hours");
					this.Onwork_hoursChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_workdays", DbType="NVarChar(50)")]
		public string workdays
		{
			get
			{
				return this._workdays;
			}
			set
			{
				if ((this._workdays != value))
				{
					this.OnworkdaysChanging(value);
					this.SendPropertyChanging();
					this._workdays = value;
					this.SendPropertyChanged("workdays");
					this.OnworkdaysChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_holidays", DbType="NVarChar(50)")]
		public string holidays
		{
			get
			{
				return this._holidays;
			}
			set
			{
				if ((this._holidays != value))
				{
					this.OnholidaysChanging(value);
					this.SendPropertyChanging();
					this._holidays = value;
					this.SendPropertyChanged("holidays");
					this.OnholidaysChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_job_name", DbType="NChar(50)")]
		public string job_name
		{
			get
			{
				return this._job_name;
			}
			set
			{
				if ((this._job_name != value))
				{
					this.Onjob_nameChanging(value);
					this.SendPropertyChanging();
					this._job_name = value;
					this.SendPropertyChanged("job_name");
					this.Onjob_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="role_employee", Storage="_employees", ThisKey="id_job", OtherKey="job_id")]
		public EntitySet<employee> employees
		{
			get
			{
				return this._employees;
			}
			set
			{
				this._employees.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_employees(employee entity)
		{
			this.SendPropertyChanging();
			entity.role = this;
		}
		
		private void detach_employees(employee entity)
		{
			this.SendPropertyChanging();
			entity.role = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.customer")]
	public partial class customer : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private System.Nullable<System.DateTime> _birthday;
		
		private string _name1;
		
		private string _name2;
		
		private int _resturant_seating;
		
		private string _telephone;
		
		private string _customer_orders;
		
		private string _user_name_;
		
		private string _password;
		
		private EntitySet<order> _orders;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnbirthdayChanging(System.Nullable<System.DateTime> value);
    partial void OnbirthdayChanged();
    partial void Onname1Changing(string value);
    partial void Onname1Changed();
    partial void Onname2Changing(string value);
    partial void Onname2Changed();
    partial void Onresturant_seatingChanging(int value);
    partial void Onresturant_seatingChanged();
    partial void OntelephoneChanging(string value);
    partial void OntelephoneChanged();
    partial void Oncustomer_ordersChanging(string value);
    partial void Oncustomer_ordersChanged();
    partial void Onuser_name_Changing(string value);
    partial void Onuser_name_Changed();
    partial void OnpasswordChanging(string value);
    partial void OnpasswordChanged();
    #endregion
		
		public customer()
		{
			this._orders = new EntitySet<order>(new Action<order>(this.attach_orders), new Action<order>(this.detach_orders));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_birthday", DbType="Date")]
		public System.Nullable<System.DateTime> birthday
		{
			get
			{
				return this._birthday;
			}
			set
			{
				if ((this._birthday != value))
				{
					this.OnbirthdayChanging(value);
					this.SendPropertyChanging();
					this._birthday = value;
					this.SendPropertyChanged("birthday");
					this.OnbirthdayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name1", DbType="NVarChar(50)")]
		public string name1
		{
			get
			{
				return this._name1;
			}
			set
			{
				if ((this._name1 != value))
				{
					this.Onname1Changing(value);
					this.SendPropertyChanging();
					this._name1 = value;
					this.SendPropertyChanged("name1");
					this.Onname1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name2", DbType="NVarChar(50)")]
		public string name2
		{
			get
			{
				return this._name2;
			}
			set
			{
				if ((this._name2 != value))
				{
					this.Onname2Changing(value);
					this.SendPropertyChanging();
					this._name2 = value;
					this.SendPropertyChanged("name2");
					this.Onname2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_resturant_seating", DbType="Int NOT NULL")]
		public int resturant_seating
		{
			get
			{
				return this._resturant_seating;
			}
			set
			{
				if ((this._resturant_seating != value))
				{
					this.Onresturant_seatingChanging(value);
					this.SendPropertyChanging();
					this._resturant_seating = value;
					this.SendPropertyChanged("resturant_seating");
					this.Onresturant_seatingChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_telephone", DbType="NVarChar(10)")]
		public string telephone
		{
			get
			{
				return this._telephone;
			}
			set
			{
				if ((this._telephone != value))
				{
					this.OntelephoneChanging(value);
					this.SendPropertyChanging();
					this._telephone = value;
					this.SendPropertyChanged("telephone");
					this.OntelephoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_customer_orders", DbType="NVarChar(50)")]
		public string customer_orders
		{
			get
			{
				return this._customer_orders;
			}
			set
			{
				if ((this._customer_orders != value))
				{
					this.Oncustomer_ordersChanging(value);
					this.SendPropertyChanging();
					this._customer_orders = value;
					this.SendPropertyChanged("customer_orders");
					this.Oncustomer_ordersChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[user_name ]", Storage="_user_name_", DbType="NVarChar(50)")]
		public string user_name_
		{
			get
			{
				return this._user_name_;
			}
			set
			{
				if ((this._user_name_ != value))
				{
					this.Onuser_name_Changing(value);
					this.SendPropertyChanging();
					this._user_name_ = value;
					this.SendPropertyChanged("user_name_");
					this.Onuser_name_Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_password", DbType="NVarChar(50)")]
		public string password
		{
			get
			{
				return this._password;
			}
			set
			{
				if ((this._password != value))
				{
					this.OnpasswordChanging(value);
					this.SendPropertyChanging();
					this._password = value;
					this.SendPropertyChanged("password");
					this.OnpasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="customer_order", Storage="_orders", ThisKey="Id", OtherKey="customer_id")]
		public EntitySet<order> orders
		{
			get
			{
				return this._orders;
			}
			set
			{
				this._orders.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_orders(order entity)
		{
			this.SendPropertyChanging();
			entity.customer = this;
		}
		
		private void detach_orders(order entity)
		{
			this.SendPropertyChanging();
			entity.customer = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.days")]
	public partial class day : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id_day;
		
		private string _day1;
		
		private System.Nullable<int> _id_resturant;
		
		private EntityRef<resturant> _resturant;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnId_dayChanging(int value);
    partial void OnId_dayChanged();
    partial void Onday1Changing(string value);
    partial void Onday1Changed();
    partial void Onid_resturantChanging(System.Nullable<int> value);
    partial void Onid_resturantChanged();
    #endregion
		
		public day()
		{
			this._resturant = default(EntityRef<resturant>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_day", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Id_day
		{
			get
			{
				return this._Id_day;
			}
			set
			{
				if ((this._Id_day != value))
				{
					this.OnId_dayChanging(value);
					this.SendPropertyChanging();
					this._Id_day = value;
					this.SendPropertyChanged("Id_day");
					this.OnId_dayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="day", Storage="_day1", DbType="NVarChar(50)")]
		public string day1
		{
			get
			{
				return this._day1;
			}
			set
			{
				if ((this._day1 != value))
				{
					this.Onday1Changing(value);
					this.SendPropertyChanging();
					this._day1 = value;
					this.SendPropertyChanged("day1");
					this.Onday1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_resturant", DbType="Int")]
		public System.Nullable<int> id_resturant
		{
			get
			{
				return this._id_resturant;
			}
			set
			{
				if ((this._id_resturant != value))
				{
					if (this._resturant.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_resturantChanging(value);
					this.SendPropertyChanging();
					this._id_resturant = value;
					this.SendPropertyChanged("id_resturant");
					this.Onid_resturantChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="resturant_day", Storage="_resturant", ThisKey="id_resturant", OtherKey="id_resturant", IsForeignKey=true)]
		public resturant resturant
		{
			get
			{
				return this._resturant.Entity;
			}
			set
			{
				resturant previousValue = this._resturant.Entity;
				if (((previousValue != value) 
							|| (this._resturant.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._resturant.Entity = null;
						previousValue.days.Remove(this);
					}
					this._resturant.Entity = value;
					if ((value != null))
					{
						value.days.Add(this);
						this._id_resturant = value.id_resturant;
					}
					else
					{
						this._id_resturant = default(Nullable<int>);
					}
					this.SendPropertyChanged("resturant");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.employees")]
	public partial class employee : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private System.Nullable<double> _salary;
		
		private string _nameone;
		
		private string _nametwo;
		
		private System.Nullable<int> _job_id;
		
		private string _phone_number;
		
		private string _user_name;
		
		private string _password;
		
		private System.Nullable<int> _id_resturant;
		
		private EntityRef<role> _role;
		
		private EntityRef<resturant> _resturant;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnsalaryChanging(System.Nullable<double> value);
    partial void OnsalaryChanged();
    partial void OnnameoneChanging(string value);
    partial void OnnameoneChanged();
    partial void OnnametwoChanging(string value);
    partial void OnnametwoChanged();
    partial void Onjob_idChanging(System.Nullable<int> value);
    partial void Onjob_idChanged();
    partial void Onphone_numberChanging(string value);
    partial void Onphone_numberChanged();
    partial void Onuser_nameChanging(string value);
    partial void Onuser_nameChanged();
    partial void OnpasswordChanging(string value);
    partial void OnpasswordChanged();
    partial void Onid_resturantChanging(System.Nullable<int> value);
    partial void Onid_resturantChanged();
    #endregion
		
		public employee()
		{
			this._role = default(EntityRef<role>);
			this._resturant = default(EntityRef<resturant>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_salary", DbType="Float")]
		public System.Nullable<double> salary
		{
			get
			{
				return this._salary;
			}
			set
			{
				if ((this._salary != value))
				{
					this.OnsalaryChanging(value);
					this.SendPropertyChanging();
					this._salary = value;
					this.SendPropertyChanged("salary");
					this.OnsalaryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nameone", DbType="NVarChar(50)")]
		public string nameone
		{
			get
			{
				return this._nameone;
			}
			set
			{
				if ((this._nameone != value))
				{
					this.OnnameoneChanging(value);
					this.SendPropertyChanging();
					this._nameone = value;
					this.SendPropertyChanged("nameone");
					this.OnnameoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nametwo", DbType="NVarChar(50)")]
		public string nametwo
		{
			get
			{
				return this._nametwo;
			}
			set
			{
				if ((this._nametwo != value))
				{
					this.OnnametwoChanging(value);
					this.SendPropertyChanging();
					this._nametwo = value;
					this.SendPropertyChanged("nametwo");
					this.OnnametwoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_job_id", DbType="Int")]
		public System.Nullable<int> job_id
		{
			get
			{
				return this._job_id;
			}
			set
			{
				if ((this._job_id != value))
				{
					if (this._role.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onjob_idChanging(value);
					this.SendPropertyChanging();
					this._job_id = value;
					this.SendPropertyChanged("job_id");
					this.Onjob_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_phone_number", DbType="NChar(10)")]
		public string phone_number
		{
			get
			{
				return this._phone_number;
			}
			set
			{
				if ((this._phone_number != value))
				{
					this.Onphone_numberChanging(value);
					this.SendPropertyChanging();
					this._phone_number = value;
					this.SendPropertyChanged("phone_number");
					this.Onphone_numberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_name", DbType="NVarChar(50)")]
		public string user_name
		{
			get
			{
				return this._user_name;
			}
			set
			{
				if ((this._user_name != value))
				{
					this.Onuser_nameChanging(value);
					this.SendPropertyChanging();
					this._user_name = value;
					this.SendPropertyChanged("user_name");
					this.Onuser_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_password", DbType="NVarChar(50)")]
		public string password
		{
			get
			{
				return this._password;
			}
			set
			{
				if ((this._password != value))
				{
					this.OnpasswordChanging(value);
					this.SendPropertyChanging();
					this._password = value;
					this.SendPropertyChanged("password");
					this.OnpasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_resturant", DbType="Int")]
		public System.Nullable<int> id_resturant
		{
			get
			{
				return this._id_resturant;
			}
			set
			{
				if ((this._id_resturant != value))
				{
					if (this._resturant.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_resturantChanging(value);
					this.SendPropertyChanging();
					this._id_resturant = value;
					this.SendPropertyChanged("id_resturant");
					this.Onid_resturantChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="role_employee", Storage="_role", ThisKey="job_id", OtherKey="id_job", IsForeignKey=true)]
		public role role
		{
			get
			{
				return this._role.Entity;
			}
			set
			{
				role previousValue = this._role.Entity;
				if (((previousValue != value) 
							|| (this._role.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._role.Entity = null;
						previousValue.employees.Remove(this);
					}
					this._role.Entity = value;
					if ((value != null))
					{
						value.employees.Add(this);
						this._job_id = value.id_job;
					}
					else
					{
						this._job_id = default(Nullable<int>);
					}
					this.SendPropertyChanged("role");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="resturant_employee", Storage="_resturant", ThisKey="id_resturant", OtherKey="id_resturant", IsForeignKey=true)]
		public resturant resturant
		{
			get
			{
				return this._resturant.Entity;
			}
			set
			{
				resturant previousValue = this._resturant.Entity;
				if (((previousValue != value) 
							|| (this._resturant.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._resturant.Entity = null;
						previousValue.employees.Remove(this);
					}
					this._resturant.Entity = value;
					if ((value != null))
					{
						value.employees.Add(this);
						this._id_resturant = value.id_resturant;
					}
					else
					{
						this._id_resturant = default(Nullable<int>);
					}
					this.SendPropertyChanged("resturant");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.menu")]
	public partial class menu : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _id_menu;
		
		private System.Nullable<System.DateTime> _start_date;
		
		private System.Nullable<System.DateTime> _end_date;
		
		private System.Nullable<int> _id_food;
		
		private string _name_menu;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_menuChanging(string value);
    partial void Onid_menuChanged();
    partial void Onstart_dateChanging(System.Nullable<System.DateTime> value);
    partial void Onstart_dateChanged();
    partial void Onend_dateChanging(System.Nullable<System.DateTime> value);
    partial void Onend_dateChanged();
    partial void Onid_foodChanging(System.Nullable<int> value);
    partial void Onid_foodChanged();
    partial void Onname_menuChanging(string value);
    partial void Onname_menuChanged();
    #endregion
		
		public menu()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_menu", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string id_menu
		{
			get
			{
				return this._id_menu;
			}
			set
			{
				if ((this._id_menu != value))
				{
					this.Onid_menuChanging(value);
					this.SendPropertyChanging();
					this._id_menu = value;
					this.SendPropertyChanged("id_menu");
					this.Onid_menuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_start_date", DbType="Date")]
		public System.Nullable<System.DateTime> start_date
		{
			get
			{
				return this._start_date;
			}
			set
			{
				if ((this._start_date != value))
				{
					this.Onstart_dateChanging(value);
					this.SendPropertyChanging();
					this._start_date = value;
					this.SendPropertyChanged("start_date");
					this.Onstart_dateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_end_date", DbType="Date")]
		public System.Nullable<System.DateTime> end_date
		{
			get
			{
				return this._end_date;
			}
			set
			{
				if ((this._end_date != value))
				{
					this.Onend_dateChanging(value);
					this.SendPropertyChanging();
					this._end_date = value;
					this.SendPropertyChanged("end_date");
					this.Onend_dateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_food", DbType="Int")]
		public System.Nullable<int> id_food
		{
			get
			{
				return this._id_food;
			}
			set
			{
				if ((this._id_food != value))
				{
					this.Onid_foodChanging(value);
					this.SendPropertyChanging();
					this._id_food = value;
					this.SendPropertyChanged("id_food");
					this.Onid_foodChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name_menu", DbType="NVarChar(50)")]
		public string name_menu
		{
			get
			{
				return this._name_menu;
			}
			set
			{
				if ((this._name_menu != value))
				{
					this.Onname_menuChanging(value);
					this.SendPropertyChanging();
					this._name_menu = value;
					this.SendPropertyChanged("name_menu");
					this.Onname_menuChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.[order]")]
	public partial class order : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _order_id;
		
		private System.Nullable<System.DateTime> _order_date;
		
		private System.Nullable<int> _customer_id;
		
		private System.Nullable<System.DateTime> _pick_up_date;
		
		private System.Nullable<int> _payment_id;
		
		private System.Nullable<int> _number_invoice;
		
		private EntitySet<food> _foods;
		
		private EntityRef<customer> _customer;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onorder_idChanging(int value);
    partial void Onorder_idChanged();
    partial void Onorder_dateChanging(System.Nullable<System.DateTime> value);
    partial void Onorder_dateChanged();
    partial void Oncustomer_idChanging(System.Nullable<int> value);
    partial void Oncustomer_idChanged();
    partial void Onpick_up_dateChanging(System.Nullable<System.DateTime> value);
    partial void Onpick_up_dateChanged();
    partial void Onpayment_idChanging(System.Nullable<int> value);
    partial void Onpayment_idChanged();
    partial void Onnumber_invoiceChanging(System.Nullable<int> value);
    partial void Onnumber_invoiceChanged();
    #endregion
		
		public order()
		{
			this._foods = new EntitySet<food>(new Action<food>(this.attach_foods), new Action<food>(this.detach_foods));
			this._customer = default(EntityRef<customer>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_order_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int order_id
		{
			get
			{
				return this._order_id;
			}
			set
			{
				if ((this._order_id != value))
				{
					this.Onorder_idChanging(value);
					this.SendPropertyChanging();
					this._order_id = value;
					this.SendPropertyChanged("order_id");
					this.Onorder_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_order_date", DbType="Date")]
		public System.Nullable<System.DateTime> order_date
		{
			get
			{
				return this._order_date;
			}
			set
			{
				if ((this._order_date != value))
				{
					this.Onorder_dateChanging(value);
					this.SendPropertyChanging();
					this._order_date = value;
					this.SendPropertyChanged("order_date");
					this.Onorder_dateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_customer_id", DbType="Int")]
		public System.Nullable<int> customer_id
		{
			get
			{
				return this._customer_id;
			}
			set
			{
				if ((this._customer_id != value))
				{
					if (this._customer.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Oncustomer_idChanging(value);
					this.SendPropertyChanging();
					this._customer_id = value;
					this.SendPropertyChanged("customer_id");
					this.Oncustomer_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pick_up_date", DbType="Date")]
		public System.Nullable<System.DateTime> pick_up_date
		{
			get
			{
				return this._pick_up_date;
			}
			set
			{
				if ((this._pick_up_date != value))
				{
					this.Onpick_up_dateChanging(value);
					this.SendPropertyChanging();
					this._pick_up_date = value;
					this.SendPropertyChanged("pick_up_date");
					this.Onpick_up_dateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_payment_id", DbType="Int")]
		public System.Nullable<int> payment_id
		{
			get
			{
				return this._payment_id;
			}
			set
			{
				if ((this._payment_id != value))
				{
					this.Onpayment_idChanging(value);
					this.SendPropertyChanging();
					this._payment_id = value;
					this.SendPropertyChanged("payment_id");
					this.Onpayment_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_number_invoice", DbType="Int")]
		public System.Nullable<int> number_invoice
		{
			get
			{
				return this._number_invoice;
			}
			set
			{
				if ((this._number_invoice != value))
				{
					this.Onnumber_invoiceChanging(value);
					this.SendPropertyChanging();
					this._number_invoice = value;
					this.SendPropertyChanged("number_invoice");
					this.Onnumber_invoiceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="order_food", Storage="_foods", ThisKey="order_id", OtherKey="id_order")]
		public EntitySet<food> foods
		{
			get
			{
				return this._foods;
			}
			set
			{
				this._foods.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="customer_order", Storage="_customer", ThisKey="customer_id", OtherKey="Id", IsForeignKey=true)]
		public customer customer
		{
			get
			{
				return this._customer.Entity;
			}
			set
			{
				customer previousValue = this._customer.Entity;
				if (((previousValue != value) 
							|| (this._customer.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._customer.Entity = null;
						previousValue.orders.Remove(this);
					}
					this._customer.Entity = value;
					if ((value != null))
					{
						value.orders.Add(this);
						this._customer_id = value.Id;
					}
					else
					{
						this._customer_id = default(Nullable<int>);
					}
					this.SendPropertyChanged("customer");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_foods(food entity)
		{
			this.SendPropertyChanging();
			entity.order = this;
		}
		
		private void detach_foods(food entity)
		{
			this.SendPropertyChanging();
			entity.order = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.resturant")]
	public partial class resturant : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_resturant;
		
		private string _id_employee;
		
		private string _discription;
		
		private System.Nullable<bool> _is_active;
		
		private System.Nullable<int> _copon;
		
		private System.Nullable<int> _work_day_id;
		
		private string _resturant_name;
		
		private System.Nullable<int> _menu_id;
		
		private EntitySet<day> _days;
		
		private EntitySet<employee> _employees;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_resturantChanging(int value);
    partial void Onid_resturantChanged();
    partial void Onid_employeeChanging(string value);
    partial void Onid_employeeChanged();
    partial void OndiscriptionChanging(string value);
    partial void OndiscriptionChanged();
    partial void Onis_activeChanging(System.Nullable<bool> value);
    partial void Onis_activeChanged();
    partial void OncoponChanging(System.Nullable<int> value);
    partial void OncoponChanged();
    partial void Onwork_day_idChanging(System.Nullable<int> value);
    partial void Onwork_day_idChanged();
    partial void Onresturant_nameChanging(string value);
    partial void Onresturant_nameChanged();
    partial void Onmenu_idChanging(System.Nullable<int> value);
    partial void Onmenu_idChanged();
    #endregion
		
		public resturant()
		{
			this._days = new EntitySet<day>(new Action<day>(this.attach_days), new Action<day>(this.detach_days));
			this._employees = new EntitySet<employee>(new Action<employee>(this.attach_employees), new Action<employee>(this.detach_employees));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_resturant", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id_resturant
		{
			get
			{
				return this._id_resturant;
			}
			set
			{
				if ((this._id_resturant != value))
				{
					this.Onid_resturantChanging(value);
					this.SendPropertyChanging();
					this._id_resturant = value;
					this.SendPropertyChanged("id_resturant");
					this.Onid_resturantChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_employee", DbType="NVarChar(50)")]
		public string id_employee
		{
			get
			{
				return this._id_employee;
			}
			set
			{
				if ((this._id_employee != value))
				{
					this.Onid_employeeChanging(value);
					this.SendPropertyChanging();
					this._id_employee = value;
					this.SendPropertyChanged("id_employee");
					this.Onid_employeeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_discription", DbType="NVarChar(50)")]
		public string discription
		{
			get
			{
				return this._discription;
			}
			set
			{
				if ((this._discription != value))
				{
					this.OndiscriptionChanging(value);
					this.SendPropertyChanging();
					this._discription = value;
					this.SendPropertyChanged("discription");
					this.OndiscriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_active", DbType="Bit")]
		public System.Nullable<bool> is_active
		{
			get
			{
				return this._is_active;
			}
			set
			{
				if ((this._is_active != value))
				{
					this.Onis_activeChanging(value);
					this.SendPropertyChanging();
					this._is_active = value;
					this.SendPropertyChanged("is_active");
					this.Onis_activeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_copon", DbType="Int")]
		public System.Nullable<int> copon
		{
			get
			{
				return this._copon;
			}
			set
			{
				if ((this._copon != value))
				{
					this.OncoponChanging(value);
					this.SendPropertyChanging();
					this._copon = value;
					this.SendPropertyChanged("copon");
					this.OncoponChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_work_day_id", DbType="Int")]
		public System.Nullable<int> work_day_id
		{
			get
			{
				return this._work_day_id;
			}
			set
			{
				if ((this._work_day_id != value))
				{
					this.Onwork_day_idChanging(value);
					this.SendPropertyChanging();
					this._work_day_id = value;
					this.SendPropertyChanged("work_day_id");
					this.Onwork_day_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_resturant_name", DbType="NVarChar(50)")]
		public string resturant_name
		{
			get
			{
				return this._resturant_name;
			}
			set
			{
				if ((this._resturant_name != value))
				{
					this.Onresturant_nameChanging(value);
					this.SendPropertyChanging();
					this._resturant_name = value;
					this.SendPropertyChanged("resturant_name");
					this.Onresturant_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_menu_id", DbType="Int")]
		public System.Nullable<int> menu_id
		{
			get
			{
				return this._menu_id;
			}
			set
			{
				if ((this._menu_id != value))
				{
					this.Onmenu_idChanging(value);
					this.SendPropertyChanging();
					this._menu_id = value;
					this.SendPropertyChanged("menu_id");
					this.Onmenu_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="resturant_day", Storage="_days", ThisKey="id_resturant", OtherKey="id_resturant")]
		public EntitySet<day> days
		{
			get
			{
				return this._days;
			}
			set
			{
				this._days.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="resturant_employee", Storage="_employees", ThisKey="id_resturant", OtherKey="id_resturant")]
		public EntitySet<employee> employees
		{
			get
			{
				return this._employees;
			}
			set
			{
				this._employees.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_days(day entity)
		{
			this.SendPropertyChanging();
			entity.resturant = this;
		}
		
		private void detach_days(day entity)
		{
			this.SendPropertyChanging();
			entity.resturant = null;
		}
		
		private void attach_employees(employee entity)
		{
			this.SendPropertyChanging();
			entity.resturant = this;
		}
		
		private void detach_employees(employee entity)
		{
			this.SendPropertyChanging();
			entity.resturant = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.food")]
	public partial class food : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_menu;
		
		private string _food_calories;
		
		private string _meal_price;
		
		private string _meal_size;
		
		private string _weight_meal;
		
		private string _meal_kind;
		
		private string _number_meal;
		
		private System.Nullable<int> _id_order;
		
		private EntityRef<order> _order;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_menuChanging(int value);
    partial void Onid_menuChanged();
    partial void Onfood_caloriesChanging(string value);
    partial void Onfood_caloriesChanged();
    partial void Onmeal_priceChanging(string value);
    partial void Onmeal_priceChanged();
    partial void Onmeal_sizeChanging(string value);
    partial void Onmeal_sizeChanged();
    partial void Onweight_mealChanging(string value);
    partial void Onweight_mealChanged();
    partial void Onmeal_kindChanging(string value);
    partial void Onmeal_kindChanged();
    partial void Onnumber_mealChanging(string value);
    partial void Onnumber_mealChanged();
    partial void Onid_orderChanging(System.Nullable<int> value);
    partial void Onid_orderChanged();
    #endregion
		
		public food()
		{
			this._order = default(EntityRef<order>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_menu", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id_menu
		{
			get
			{
				return this._id_menu;
			}
			set
			{
				if ((this._id_menu != value))
				{
					this.Onid_menuChanging(value);
					this.SendPropertyChanging();
					this._id_menu = value;
					this.SendPropertyChanged("id_menu");
					this.Onid_menuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_food_calories", DbType="NVarChar(50)")]
		public string food_calories
		{
			get
			{
				return this._food_calories;
			}
			set
			{
				if ((this._food_calories != value))
				{
					this.Onfood_caloriesChanging(value);
					this.SendPropertyChanging();
					this._food_calories = value;
					this.SendPropertyChanged("food_calories");
					this.Onfood_caloriesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_meal_price", DbType="NVarChar(50)")]
		public string meal_price
		{
			get
			{
				return this._meal_price;
			}
			set
			{
				if ((this._meal_price != value))
				{
					this.Onmeal_priceChanging(value);
					this.SendPropertyChanging();
					this._meal_price = value;
					this.SendPropertyChanged("meal_price");
					this.Onmeal_priceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_meal_size", DbType="NVarChar(50)")]
		public string meal_size
		{
			get
			{
				return this._meal_size;
			}
			set
			{
				if ((this._meal_size != value))
				{
					this.Onmeal_sizeChanging(value);
					this.SendPropertyChanging();
					this._meal_size = value;
					this.SendPropertyChanged("meal_size");
					this.Onmeal_sizeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_weight_meal", DbType="NVarChar(50)")]
		public string weight_meal
		{
			get
			{
				return this._weight_meal;
			}
			set
			{
				if ((this._weight_meal != value))
				{
					this.Onweight_mealChanging(value);
					this.SendPropertyChanging();
					this._weight_meal = value;
					this.SendPropertyChanged("weight_meal");
					this.Onweight_mealChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_meal_kind", DbType="NVarChar(50)")]
		public string meal_kind
		{
			get
			{
				return this._meal_kind;
			}
			set
			{
				if ((this._meal_kind != value))
				{
					this.Onmeal_kindChanging(value);
					this.SendPropertyChanging();
					this._meal_kind = value;
					this.SendPropertyChanged("meal_kind");
					this.Onmeal_kindChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_number_meal", DbType="NVarChar(50)")]
		public string number_meal
		{
			get
			{
				return this._number_meal;
			}
			set
			{
				if ((this._number_meal != value))
				{
					this.Onnumber_mealChanging(value);
					this.SendPropertyChanging();
					this._number_meal = value;
					this.SendPropertyChanged("number_meal");
					this.Onnumber_mealChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_order", DbType="Int")]
		public System.Nullable<int> id_order
		{
			get
			{
				return this._id_order;
			}
			set
			{
				if ((this._id_order != value))
				{
					if (this._order.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_orderChanging(value);
					this.SendPropertyChanging();
					this._id_order = value;
					this.SendPropertyChanged("id_order");
					this.Onid_orderChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="order_food", Storage="_order", ThisKey="id_order", OtherKey="order_id", IsForeignKey=true)]
		public order order
		{
			get
			{
				return this._order.Entity;
			}
			set
			{
				order previousValue = this._order.Entity;
				if (((previousValue != value) 
							|| (this._order.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._order.Entity = null;
						previousValue.foods.Remove(this);
					}
					this._order.Entity = value;
					if ((value != null))
					{
						value.foods.Add(this);
						this._id_order = value.order_id;
					}
					else
					{
						this._id_order = default(Nullable<int>);
					}
					this.SendPropertyChanged("order");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
